# Generated by Django 3.0.5 on 2020-06-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
