# Generated by Django 3.0.5 on 2020-05-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('descripyion', models.TextField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=15)),
            ],
        ),
    ]
